<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vrnnb-prc498" ignored="0" name="Command line test" tests="3" failures="1" timestamp="2021-03-16T15:54:36 MSK" time="0.058" errors="0">
  <testcase name="first" time="0.007" classname="regress.Test1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at regress.Test1.first(Test1.java:11)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- first -->
  <testcase name="second" time="0.0" classname="regress.Test1"/>
  <testcase name="third" time="0.001" classname="regress.Test1"/>
</testsuite> <!-- Command line test -->
